version: '3'

services:

  mysql-simba:
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: hellosimba
    volumes:
      - ./init-files:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"

