insert into customers (first_name, phone, instagram) values ('Алена', '093 455 48 87', '_alionka_k');
insert into customers (first_name, phone, instagram) values ('Оксана', '093 484 94 09', '_oksana_skubak_');
insert into customers (first_name, last_name, phone, instagram, notes) values ('Александра', 'Ходоренко', '063 860 89 91', '_smska_', 'старая знакомая Оли');
insert into customers (first_name, phone, instagram) values ('Анна', '098 886 58 25', 'a.alekseyenko');
insert into customers (first_name, phone, instagram) values ('Алексей', '067 465 75 89',  'acula1990/ от марии ткач');
insert into customers (first_name, phone, instagram) values ('Александра', '096 632 22 51',  'alika_klim');
insert into customers (first_name, last_name, phone, instagram, notes) values ('Алина', 'Бекрешова', '063 438 0919 ','alinabekreshova', 'Долгое время была постоянным клиентом, заказывала каждую неделю, предпологаем что стало меньше денег');
insert into customers (first_name, phone, instagram) values ('Альона', '097 902 60 14', 'aliona_saikivska');
insert into customers (first_name, phone, instagram) values ('Алена', '067 240 61 01',  'alena_khoroshun');
insert into customers (first_name, last_name, phone, instagram) values ('Алла', 'Левицка', '050 530 10 88',  'alla_levytska');
insert into customers (first_name, phone, instagram) values ('Алена', '067 998 22 29',  'alyona_busen6');
insert into customers (first_name, phone, instagram) values ('Анастасия', '097 311 60 28', 'anastasiy_2209/вайбер');
insert into customers (first_name, phone, instagram) values ('Юлия', '063 269 14 81',  'andomiulka');
insert into customers (first_name, phone, instagram) values ('Людмила', '097 674 44 67', 'andronova_lydmila');
insert into customers (first_name, phone, instagram, notes) values ('Татьяна', '063 388 84 67', 'andronova_tetiana', 'постоянный клиент/ один раз привезли случайно класичне вместо лайт');
insert into customers (first_name, phone, instagram, notes) values ('Анна', '1',  'aniutakotenko', 'раньше заказывала каждую неделю, сейчас ей блюда нравятся меньше чем старые, 27 сентября пісала что сделает паузу ізза фінанс трудностей');
insert into customers (first_name, phone, instagram) values ('Анна', '093 710 60 69', 'anjashka');
insert into customers (first_name, phone, instagram, notes) values ('Анна', '097 300 55 94',  'annagrom', 'раньше заказывала постоянно, в первых числах августа "родили принцессу", пока на грудном вскармлевании, последний раз писали 12 сентября, все еще не кушает все');
insert into customers (first_name, phone, instagram) values ('Анна', '050 883 98 91',  'anuta_fedoseenko');
insert into customers (first_name, phone, instagram) values ('Анна', '050 733 99 73',  'anya_kusochek');
insert into customers (first_name, phone, instagram) values ('Анна', '063 890 64 55', 'anya_musiiuk');
insert into customers (first_name, phone, instagram, notes) values ('Виктория', '050 463 82 66', 'bandykvictoria',  'код 2');
insert into customers (first_name, phone, instagram) values ('Елена', '093 093 92 52', 'belo4kasmail');
insert into customers (first_name, phone, instagram, notes) values ('Божена', '095 143 37 25', 'bojena_shvedova', 'Блогер, аккаунт выглядит так будто переехала в Мо');
insert into customers (first_name, last_name, phone, instagram) values ('Юлия', 'Бондаренко', '050 352 81 39', 'bonjuleta');
insert into customers (first_name, phone, instagram) values ('Мария', '093 278 66 12', 'bro_masha__/телега');
insert into customers (first_name, phone, instagram) values ('Людмила', '099 717 37 59',  'cudrya_');
insert into customers (first_name, phone, instagram) values ('Даня', '095 011 09 29',  'danni4ka');
insert into customers (first_name, phone, instagram) values ('Наталья', '098 383 31 04',  'danyliuknataliia');
insert into customers (first_name, phone, instagram) values ('Дарья', '050 044 28 80', 'darialysyak');
insert into customers (first_name, phone, instagram) values ('Дарья', '066  511 20 3', 'dashakim');
insert into customers (first_name, phone, instagram) values ('Марина', '066 339 48 55', 'davidenko_marina');
insert into customers (first_name, phone, instagram, notes) values ('Анна', '099 021 93 05',  'designed_by_anna_foxy', 'часто заказывает, почти постоянно');
insert into customers (first_name, phone, instagram) values ('Евгения', '093 428 00 07', 'dr_andreeva');
insert into customers (first_name, phone, instagram, notes) values ('Anna', '050 915 96 66', 'dreamlys', 'писала что хотела заказать лайт но уезжает, так и не заказала, умеет готовить, как-то раз записала нам свой вариант рецепта');
insert into customers (first_name, last_name, phone, instagram, notes) values ('Величко', 'Анастасия', '093 223 24 63', 'efta_tak', 'раньше брала довольно часто');
insert into customers (first_name, phone, instagram) values ('Елена ', '095 140 32 39',  'elena_tsenkush');
insert into customers (first_name, phone, instagram, notes) values ('Елена ', '067 913 11 31', 'evnekrasova/evlykova или вайбер', 'заказывала часто');
insert into customers (first_name, phone, instagram) values ('Ника', '067 592 97 46',  'fire__nika');
insert into customers (first_name, phone, instagram, notes) values ('Евгения', '097-640-09-03',  'genechka2013', 'В начале проекта была постоянным клиентом');
insert into customers (first_name, phone, instagram) values ('Галина', '068 138 00 01', 'gle350d_');
insert into customers (first_name, phone, instagram) values ('Маргарита', '066 855 92 23',  'happy_and_healthy_margarita');
insert into customers (first_name, phone, instagram) values ('Евгенія', '063 678 49 96',  'ievgeniialubchenko');
insert into customers (first_name, phone, instagram) values ('Инна', '050 133 94 43','innita79');
insert into customers (first_name, phone, instagram) values ('Ира', '050 671 98 87', 'ira_evavera');
insert into customers (first_name, phone, instagram) values ('Ирина', '093 689 00 41',  'ira_kharieva');
insert into customers (first_name, phone, instagram, notes) values ('Ирина', '097 469 22 83', 'irenmiren',  'дзвонити домофон не працює');
insert into customers (first_name, phone, instagram) values ('Ирина', '067 326 98 06', 'irina_irina69ВАЙБЕР/телеграм');
insert into customers (first_name, last_name, phone, instagram) values ('Ирина', 'Кардашева', '063 026 37 80', 'iriskabro');
insert into customers (first_name, last_name, phone, instagram) values ('Юля', 'Тимофеева', '050 849 41 61', 'iuliia.timofeeva');
insert into customers (first_name, phone, instagram) values ('Евгения', '063 179 86 02', 'janedzyuban');
insert into customers (first_name, phone, instagram) values ('Евгения', '095 888 88 51',  'janesimonova');
insert into customers (first_name, last_name, phone, instagram, notes) values ('Женя', 'Бондаренко', '063 20 22 521',  'jenechka_bondarenko', 'была постоянным клиентом, как-то раз у нее испортился сыр, изинились, сделали скидку, продолжила заказывать, через какое-то время ей попался перец свежий снаружи, испорченный внутри (попалась хреновая партия перцев), извинились сделали скидку, заказала еще раза 3 и перестала');
insert into customers (first_name, phone, instagram) values ('Юлия', '093 470 80 90', 'julia_fed4enko');
insert into customers (first_name, last_name, phone, instagram, notes) values ('Юлиана', 'Хижняк', '063 963 92 25',  'juliana_khyzh', 'женщина которая не поняла замороженный манго, после чего перестала заказывать, не любит сельдерей, говорит у нас его сильно много в блюдах. До этого заказывала часто и хвалила нас');
insert into customers (first_name, phone, instagram, notes) values ('Юлия', '067 695 56 20',  'juliia_ivankina', 'от блогера');
insert into customers (first_name, phone, instagram) values ('Екатерина', '099 946 55 36',  'kaci_kaci');
insert into customers (first_name, last_name, phone, instagram) values ('Катерина', 'Беседина', '093 722 21 64',  'kate.besedina');
insert into customers (first_name, phone, instagram) values ('Катя', 'глуш', 'kate.not.katya');
insert into customers (first_name, last_name, phone, instagram) values ('Ященко', 'Катя', '050 93 11 999', 'katrin__ya');
insert into customers (first_name, phone, instagram, notes) values ('Кристина', '067 676 76 93',  'khrystyna_ivanenko', 'часто делает заказ/ не будет заказывать до конца октября, начнет с ноября');
insert into customers (first_name, last_name, phone, instagram) values ('Микиртумова', 'Диана', '066 793 73 78', 'klyulov_ka');
insert into customers (first_name, phone, instagram) values ('Татьяна', '063 850 66 16', 'koinlove');
insert into customers (first_name, last_name, phone, instagram, notes) values ('Костеева', 'Татьяна', '097 019 63 93', 'kosteevatatiana', 'сказала встретимся снова в сентябре, пока не встречались');
insert into customers (first_name, phone, instagram) values ('Кристина', '097 701 72 57', 'kristinabolokhova');
insert into customers (first_name, phone, instagram) values ('Людмила', '067 791 62 50', 'ludmila.bahmut');
insert into customers (first_name, phone, instagram) values ('Людмила', '093 676 07 27', 'lyudmilabotsko');
insert into customers (first_name, phone, instagram) values ('Диана', '093 987 00 73', 'm_dia13');
insert into customers (first_name, phone, instagram) values ('Мария', '063 744 11 59', 'mariiatkach');
insert into customers (first_name, phone, instagram) values ('Марина', '097 100 28 67', 'marina_gordii');
insert into customers (first_name, phone, instagram) values ('Марта', '063 523 24 01', 'Marta_skurska');
insert into customers (first_name, phone, instagram) values ('Мария', '093 94 90 409', 'maruskazavialova');
insert into customers (first_name, phone, instagram) values ('Марьяна', '093 386 36 19', 'maryanastavreva');
insert into customers (first_name, phone, instagram, notes) values ('Марина', '063 585 86 87','maryna_kaspy', 'код 385');
insert into customers (first_name, phone, instagram) values ('Марина', '093 521 61 43', 'marynaischenlo');
insert into customers (first_name, phone, instagram) values ('Мила', '066 384 04 42',  'milazhekova');
insert into customers (first_name, phone, instagram) values ('Мирослава', '050 995 17 88', 'miroslava.vv');
insert into customers (first_name, last_name, phone, instagram) values ('Анастасию', 'Зюкова', '098 919 69 28', 'n_zyukova');
insert into customers (first_name, phone, instagram) values ('Наталья', '097 620 08 14',  'natalya_zhuravel');
insert into customers (first_name, phone, instagram) values ('Нелли', '093 862 41 53',  'nelli_kokorina');
insert into customers (first_name, phone, instagram) values ('Вероника', '097 177 40 50', 'nikamach');
insert into customers (first_name, phone, instagram) values ('Юлія', '093 456 11 13',  'novosvitnaya_julia');
insert into customers (first_name, phone, instagram) values ('Оксана', '050 285 00 97', 'oksana_kobzina');
insert into customers (first_name, phone, instagram) values ('Оксана', '097 024 24 64', 'oksanochhhka');
insert into customers (first_name, phone, instagram) values ('Олена', '050 278 84 74',  'olena_1545');
insert into customers (first_name, phone, instagram) values ('Olga', '066 060 98 13', 'olga_gets');
insert into customers (first_name, phone, instagram) values ('Ольга', '050 383 89 08', 'olgakhor')