version: '3'

services:

  mysql-simba:
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: hellosimba
      MYSQL_DATABASE: simba
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    ports:
      - "3308:3306"

