insert into ingredients(description, unit, art_by) values ('Черника замороженная', 'кг', '9810144'); 
insert into ingredients(description, unit, art_by) values ('Ванильный сахар', 'кг', '9810178'); 
insert into ingredients(description, unit, art_by) values ('Крупа Манная', 'кг', '52084'); 
insert into ingredients(description, unit, art_by) values ('Мука пш. в/с марка М54-25 "Лидахлебпродукт", ф.2кг', 'кг', '53414'); 
insert into ingredients(description, unit, art_by) values ('Яйцо куриное С1 10 шт', 'шт', '51050'); 
insert into ingredients(description, unit, art_by) values ('Творог', 'кг', '9808788'); 

insert into ingredients(description, unit, art_by) values ('Мука пш. в/с марка М54-28 "Лидахлебпродукт", ф.2кг', 'кг', '50110'); 
insert into ingredients(description, unit, art_by) values ('Сметана', 'кг', '21247'); 
insert into ingredients(description, unit, art_by) values ('Сыр Российский (кг)', 'кг', '9808339'); 
insert into ingredients(description, unit, art_by) values ('Продукт из свинины коп.-вар. мясной "Ветчина "Домашняя"', 'кг', '52102'); 
insert into ingredients(description, unit, art_by) values ('Сахар "Радуга" 5г', 'кг', '52413'); 
insert into ingredients(description, unit, art_by) values ('Яйцо куриное С1 10 шт', 'шт', '51050'); 
insert into ingredients(description, unit, art_by) values ('Молоко детское, 3,2% 0,2л', 'кг', '52081'); 

insert into ingredients(description, unit, art_by) values ('Масло сладкосливочное', 'кг', '52036'); 
insert into ingredients(description, unit, art_by) values ('Корица молотая', 'кг', '52088'); 
insert into ingredients(description, unit, art_by) values ('Яблоко', 'кг', '50947'); 
insert into ingredients(description, unit, art_by) values ('Сахар белый кристаллический (фасованный), 1 кг', 'кг', '6265'); 
insert into ingredients(description, unit, art_by) values ('Мед натуральный алюм.конт., 25г', 'кг', '52764'); 
insert into ingredients(description, unit, art_by) values ('Молоко детское, 3,2% 0,2л', 'кг', '52081'); 
insert into ingredients(description, unit, art_by) values ('Рис длинный "Жасмин" фас. 0,8 кг цвет.', 'кг', '5900'); 

insert into ingredients(description, unit, art_by) values ('Колбаса сырокопченая САЛЯМИ ТРАДИЦИОННАЯ (НАРЕЗКА) 90 г (мгс)', 'кг', '50322'); 
insert into ingredients(description, unit, art_by) values ('Приправа паприка', 'кг', '52358'); 
insert into ingredients(description, unit, art_by) values ('Приправа прованские травы', 'кг', '52005'); 
insert into ingredients(description, unit, art_by) values ('Петрушка листовая', 'кг', '50952'); 
insert into ingredients(description, unit, art_by) values ('Лук-шалот', 'кг', '51068'); 
insert into ingredients(description, unit, art_by) values ('Перец желтый', 'кг', '50938'); 
insert into ingredients(description, unit, art_by) values ('Капуста брокколи быстрозамороженная 1 уп/1кг  тм DUJARDIN', 'кг', '51034'); 
insert into ingredients(description, unit, art_by) values ('Яйцо куриное С1 10 шт', 'шт', '51050'); 

insert into ingredients(description, unit, art_by) values ('Тостовый хлеб зерновой 800 г,  1кор./6 шт./4,80 кг', 'кг', '52926'); 
insert into ingredients(description, unit, art_by) values ('Уксус спиртовой пищ. 9%', 'л', '51106'); 
insert into ingredients(description, unit, art_by) values ('Уксус Modena бальзамический 6% тм Ponti, 1бут/500мл', 'кг', '5543'); 
insert into ingredients(description, unit, art_by) values ('Петрушка листовая', 'кг', '50952'); 
insert into ingredients(description, unit, art_by) values ('Сыр мягкий Арла Натура с травами и специями массовая доля жира в сухом веществе 50%, 1уп/ 150гр', 'кг', '5650'); 
insert into ingredients(description, unit, art_by) values ('Консервы рыбные стерилизованные Тунец КУСОЧКАМИ В СОБСТВЕННОМ СОКУ тм Morrel, ж/б 185г', 'кг', '50183'); 
insert into ingredients(description, unit, art_by) values ('Чеснок', 'кг', '50964'); 
insert into ingredients(description, unit, art_by) values ('Лук красный', 'кг', '50934'); 
insert into ingredients(description, unit, art_by) values ('Яйцо куриное С1 10 шт', 'шт', '51050'); 
insert into ingredients(description, unit, art_by) values ('Фасоль белая 400г ж/б', 'кг', '21241'); 

insert into ingredients(description, unit, art_by) values ('СОУС ГОРЧИЧНЫЙ. СОУС НА ОСНОВЕ РАСТИТЕЛЬНЫХ МАСЕЛ (ХАЙНЦ) 25 МЛ (РОССИЯ)', 'кг', '50900'); 
insert into ingredients(description, unit, art_by) values ('Томаты резаные очищенные тм DueFagiani, 1 бан /4,05кг', 'кг', '50606'); 
insert into ingredients(description, unit, art_by) values ('Горчица пищевая Боярская АВС сашет, 15г', 'кг', '52718'); 
insert into ingredients(description, unit, art_by) values ('Кукуруза в зернах быстрозамороженная 1 уп/1кг тм DUJARDIN', 'кг', '51038'); 
insert into ingredients(description, unit, art_by) values ('Орегано сушеный', 'кг', '52506'); 
insert into ingredients(description, unit, art_by) values ('Чеснок сушеный гранулы', 'кг', '52507'); 
insert into ingredients(description, unit, art_by) values ('Тмин зерно', 'кг', '52021'); 
insert into ingredients(description, unit, art_by) values ('Паприка копченая (кг)', 'кг', '9808236'); 
insert into ingredients(description, unit, art_by) values ('Сыр плавленый ломтевой "Бистро" Чеддер  45% Хохланд (Россия) 1,033 кг/уп, (84 шт)', 'кг', '50517'); 
insert into ingredients(description, unit, art_by) values ('Паста томатная 500гр', 'кг', '52225'); 
insert into ingredients(description, unit, art_by) values ('Лук репчатый', 'кг', '50933'); 
insert into ingredients(description, unit, art_by) values ('П-ф  мясной натур из говядины "Котлетное мясо говяжье"замороженный', 'кг', '51235'); 
insert into ingredients(description, unit, art_by) values ('СОСИСКИ "ДЕЛИКАТЕСНЫЕ" изделие колбасное мясное вареное,  0,200 кг, в/у', 'кг', '52873'); 
insert into ingredients(description, unit, art_by) values ('БУЛОЧКА ДЛЯ ДАТСКОГО ХОТ-ДОГА"MAXI" 60 Г LANTMANNEN UNIBAKE', 'шт', '52445'); 

insert into ingredients(description, unit, art_by) values ('Масло сладкосливочное', 'кг', '52036'); 
insert into ingredients(description, unit, art_by) values ('Чеснок', 'кг', '50964'); 
insert into ingredients(description, unit, art_by) values ('Томаты резаные очищенные тм DueFagiani, 1 бан /4,05кг', 'кг', '50606'); 
insert into ingredients(description, unit, art_by) values ('Сухари панировочные (PANKO BREAD CRUMBS) 1/15кг (ИНДИЯ)', 'кг', '50203'); 
insert into ingredients(description, unit, art_by) values ('Макаронные изделия DIVELLA № 40 Fusilli "Спиральки" 500 г', 'кг', '52513'); 
insert into ingredients(description, unit, art_by) values ('Лук репчатый', 'кг', '50933'); 
insert into ingredients(description, unit, art_by) values ('Чернослив сушенный б/к', 'кг', '51100'); 
insert into ingredients(description, unit, art_by) values ('ИМ Простоквашино Сливки, 10%, 20г', 'кг', '52570'); 
insert into ingredients(description, unit, art_by) values ('Филе индейки фас. в лоток', 'кг', '50726'); 
insert into ingredients(description, unit, art_by) values ('Корнишоны маринованные 680г ст/б ', 'кг', '52253'); 
insert into ingredients(description, unit, art_by) values ('Укроп сушеный (кг)', 'кг', '9808747'); 

insert into ingredients(description, unit, art_by) values ('Макарон. изд. " Pasta Zara"  Кус-Кус №185 0,5 кг (группа "А", в/с)', 'кг', '52093'); 
insert into ingredients(description, unit, art_by) values ('Спаржа зеленая с/м  упак/1кг', 'кг', '50145'); 
insert into ingredients(description, unit, art_by) values ('Приправа карри', 'кг', '52046'); 
insert into ingredients(description, unit, art_by) values ('Приправа паприка', 'кг', '52358'); 
insert into ingredients(description, unit, art_by) values ('Чеснок сушеный гранулы', 'кг', '52507'); 
insert into ingredients(description, unit, art_by) values ('Сельдерей стебель', 'кг', '50954'); 
insert into ingredients(description, unit, art_by) values ('Лук порей', 'кг', '50932'); 
insert into ingredients(description, unit, art_by) values ('Чеснок', 'кг', '50964'); 
insert into ingredients(description, unit, art_by) values ('П/ф из мяса птицы Мякоть бедра ЦБ (Ганна) упак в средний лоток и г/я', 'кг', '52816'); 
insert into ingredients(description, unit, art_by) values ('Имбирь', 'кг', '50926'); 

insert into ingredients(description, unit, art_by) values ('Чеснок сушеный гранулы', 'кг', '52507'); 
insert into ingredients(description, unit, art_by) values ('Зира-кумин (кг)', 'кг', '9808301'); 
insert into ingredients(description, unit, art_by) values ('Кориандр приправа', 'кг', '51163'); 
insert into ingredients(description, unit, art_by) values ('Сливки питьевые стерилизованные 20%, 200 г', 'кг', '52227'); 
insert into ingredients(description, unit, art_by) values ('Яйцо куриное С1 10 шт', 'шт', '51050'); 
insert into ingredients(description, unit, art_by) values ('Мука пш. в/с марка М54-28 "Лидахлебпродукт", ф.2кг', 'кг', '50110'); 
insert into ingredients(description, unit, art_by) values ('Масло сладкосливочное', 'кг', '52036'); 
insert into ingredients(description, unit, art_by) values ('Лук репчатый', 'кг', '50933'); 
insert into ingredients(description, unit, art_by) values ('Лук порей', 'кг', '50932'); 
insert into ingredients(description, unit, art_by) values ('Грибы белые быстрозамороженные резаные, фас. 1/300 ', 'кг', '5981'); 
insert into ingredients(description, unit, art_by) values ('Перец желтый', 'кг', '50938'); 
insert into ingredients(description, unit, art_by) values ('Картофель ', 'кг', '50931'); 
insert into ingredients(description, unit, art_by) values ('П/ф мясной "Вырезка свиная" замороженный', 'кг', '50973'); 

insert into ingredients(description, unit, art_by) values ('KNORR Primerba Приправа в растительном масле Травы Прованса 340 г.', 'кг', '50630'); 
insert into ingredients(description, unit, art_by) values ('Мед натуральный алюм.конт., 25г', 'кг', '52764'); 
insert into ingredients(description, unit, art_by) values ('Горчица АВС Французская 160гр', 'кг', '52757'); 
insert into ingredients(description, unit, art_by) values ('Kikkoman Соевый соус 19л, Bag & Box, Нидерланды', 'кг', '16'); 
insert into ingredients(description, unit, art_by) values ('Масло сладкосливочное', 'кг', '52036'); 
insert into ingredients(description, unit, art_by) values ('Морковь', 'кг', '50935'); 
insert into ingredients(description, unit, art_by) values ('Капуста брокколи быстрозамороженная 1 уп/1кг  тм DUJARDIN', 'кг', '51034'); 
insert into ingredients(description, unit, art_by) values ('Сельдерей стебель', 'кг', '50954'); 
insert into ingredients(description, unit, art_by) values ('Шампиньоны (выбирать)', 'кг', '50966'); 
insert into ingredients(description, unit, art_by) values ('Филе лосося с кожей ТРИМ D, 1500-2500 г', 'кг', '52082'); 

insert into ingredients(description, unit, art_by) values ('Мед натуральный алюм.конт., 25г', 'кг', '52764'); 
insert into ingredients(description, unit, art_by) values ('Петрушка листовая', 'кг', '50952'); 
insert into ingredients(description, unit, art_by) values ('Тимьян', 'кг', '50962'); 
insert into ingredients(description, unit, art_by) values ('Томат черри', 'кг', '50945'); 
insert into ingredients(description, unit, art_by) values ('Морковь', 'кг', '50935'); 
insert into ingredients(description, unit, art_by) values ('Редис красный', 'кг', '50941'); 
insert into ingredients(description, unit, art_by) values ('Стручковая фасоль МЕЛКАЯ быстрозамороженная 1уп/1кг тм DUJARDIN', 'кг', '51044'); 
insert into ingredients(description, unit, art_by) values ('Лук репчатый', 'кг', '50933'); 
insert into ingredients(description, unit, art_by) values ('Филе индейки фас. в лоток', 'кг', '50726'); 

insert into ingredients(description, unit, art_by) values ('Петрушка листовая', 'кг', '50952'); 
insert into ingredients(description, unit, art_by) values ('Сок лимонный восстановленный', 'л', '9808303'); 
insert into ingredients(description, unit, art_by) values ('Ядро подсолнечника ', 'кг', '51152'); 
insert into ingredients(description, unit, art_by) values ('Томат черри', 'кг', '50945'); 
insert into ingredients(description, unit, art_by) values ('Перец красный сладкий "лепестки" (кг)', 'кг', '51003'); 
insert into ingredients(description, unit, art_by) values ('Стручковая фасоль РЕЗАНАЯ быстрозамороженная 1уп/1кг тм DUJARDIN', 'кг', '51045'); 
insert into ingredients(description, unit, art_by) values ('Рис длинный "Басмати" фас. 0,8 кг', 'кг', '6188'); 
insert into ingredients(description, unit, art_by) values ('Чеснок', 'кг', '50964'); 
insert into ingredients(description, unit, art_by) values ('Сыр твердый ГРАНА ПАДАНО тм Granarolo, м.д. жира в с.в. 32%, 1 уп./~1 кг (весовой), в/у', 'кг', '52485'); 
insert into ingredients(description, unit, art_by) values ('Мелкий горошек быстрозамороженный 1уп/1кг тм DUJARDIN', 'кг', '51041'); 
insert into ingredients(description, unit, art_by) values ('Сыр мягкий "Рикотта" с массовой долей жира в сухомвеществе 50 %, 200 г (2х100 г)', 'кг', '52024'); 
insert into ingredients(description, unit, art_by) values ('KNORR Primerba Приправа в растительном масле Базилик 340 г.', 'кг', '50628'); 
insert into ingredients(description, unit, art_by) values ('КНОРР Вяленые томаты в подсолнечном масле и винном уксусе (Италия) 750 г', 'кг', '50557'); 
insert into ingredients(description, unit, art_by) values ('Филе  ЦБ большое зам. (Ганна), упак в  лоток  и г/я', 'кг', '52863'); 

insert into ingredients(description, unit, art_by) values ('Петрушка листовая', 'кг', '50952'); 
insert into ingredients(description, unit, art_by) values ('Тимьян', 'кг', '50962'); 
insert into ingredients(description, unit, art_by) values ('Горчица АВС Французская 160гр', 'кг', '52757'); 
insert into ingredients(description, unit, art_by) values ('Лук красный', 'кг', '50934'); 
insert into ingredients(description, unit, art_by) values ('Паста Томатная АВС ст/бан, 500г', 'кг', '53156'); 
insert into ingredients(description, unit, art_by) values ('Морковь', 'кг', '50935'); 
insert into ingredients(description, unit, art_by) values ('Перец желтый', 'кг', '50938'); 
insert into ingredients(description, unit, art_by) values ('Чеснок', 'кг', '50964'); 
insert into ingredients(description, unit, art_by) values ('Томат', 'кг', '50944'); 
insert into ingredients(description, unit, art_by) values ('Мерзула аргентинская филе без кожи 60-120г(хек) мор. кат. А 1/0,5кг 1*20', 'кг', '53403'); 

insert into ingredients(description, unit, art_by) values ('Соус сладкий чили для обмакивания с чесноком (пласт.уп.) т.м. Голубой дракон, 500 г', 'кг', '50451'); 
insert into ingredients(description, unit, art_by) values ('Салат Айсберг', 'кг', '50955'); 
insert into ingredients(description, unit, art_by) values ('Перец желтый', 'кг', '50938'); 
insert into ingredients(description, unit, art_by) values ('Knorr Острая паста из морепродуктов 500г', 'кг', '50461'); 
insert into ingredients(description, unit, art_by) values ('КРЕВЕТКИ ваннамей с/м б/г 21/25 25-35% 1 кг, NAIK, Индия', 'кг', '52527'); 
insert into ingredients(description, unit, art_by) values ('Вермишель крахмальная Фунчоза"Kekeshi" в брикетах 500г', 'кг', '53198'); 
insert into ingredients(description, unit, art_by) values ('Огурец', 'кг', '50936'); 
insert into ingredients(description, unit, art_by) values ('Морковь', 'кг', '50935'); 
insert into ingredients(description, unit, art_by) values ('Рисовая бумага для роллов "Спринг роллз" т.м. Голубой дракон, 134 гр', 'кг', '5801'); 

insert into ingredients(description, unit, art_by) values ('МАСЛО оливковое Extra Virgin, пэт 5 л, Regina, Италия', 'кг', '52459'); 
insert into ingredients(description, unit, art_by) values ('Сахар "Радуга" 5г', 'кг', '52413'); 
insert into ingredients(description, unit, art_by) values ('Уксус Modena бальзамический 6% тм Ponti, 1бут/500мл', 'кг', '5543'); 
insert into ingredients(description, unit, art_by) values ('Горчица АВС Французская 160гр', 'кг', '52757'); 
insert into ingredients(description, unit, art_by) values ('Горчица Дижонская "Борнье" 1бан/0,37 кг, Франция', 'кг', '5636'); 
insert into ingredients(description, unit, art_by) values ('Сыр твердый ГРАНА ПАДАНО тм Granarolo, м.д. жира в с.в. 32%, 1 уп./~1 кг (весовой), в/у', 'кг', '52485'); 
insert into ingredients(description, unit, art_by) values ('Томат черри', 'кг', '50945'); 
insert into ingredients(description, unit, art_by) values ('Салатная смесь Микс №1 "Антонио"', 'кг', '52750'); 
insert into ingredients(description, unit, art_by) values ('Чеснок', 'кг', '50964'); 
insert into ingredients(description, unit, art_by) values ('Kikkoman Соевый соус 19л, Bag & Box, Нидерланды', 'кг', '16'); 
insert into ingredients(description, unit, art_by) values ('Розмарин', 'кг', '50953'); 
insert into ingredients(description, unit, art_by) values ('П/ф мясной "Вырезка говяжья" замороженный', 'кг', '50969'); 

insert into ingredients(description, unit, art_by) values ('Пудра сахарная свекловичная, 1 шт/350 г', 'кг', '6264'); 
insert into ingredients(description, unit, art_by) values ('Творог "Простоквашино" мас.д.ж.  9%, 180 г', 'кг', '9810491'); 
insert into ingredients(description, unit, art_by) values ('Яйцо куриное С1 10 шт', 'шт', '51050'); 
insert into ingredients(description, unit, art_by) values ('Мука пш. в/с марка М54-28 "Лидахлебпродукт", ф.2кг', 'кг', '50110'); 
insert into ingredients(description, unit, art_by) values ('Масло сладкосливочное', 'кг', '52036'); 

insert into ingredients(description, unit, art_by) values ('Тыква', 'кг', '50946'); 
insert into ingredients(description, unit, art_by) values ('Петрушка листовая', 'кг', '50952'); 
insert into ingredients(description, unit, art_by) values ('Масло сладкосливочное', 'кг', '52036'); 
insert into ingredients(description, unit, art_by) values ('Семена тыквы', 'кг', '803884'); 
insert into ingredients(description, unit, art_by) values ('Лук-шалот', 'кг', '51068'); 
insert into ingredients(description, unit, art_by) values ('Имбирь', 'кг', '50926'); 
insert into ingredients(description, unit, art_by) values ('Мини багет 45г тм BRIDOR  (замороженный полуфабрикат хлебобулочного изделия из муки)', 'кг', '51113'); 
insert into ingredients(description, unit, art_by) values ('Мускатный орех молотый', 'кг', '52057'); 
insert into ingredients(description, unit, art_by) values ('Сливки питьевые стерилизованные 20%, 200 г', 'кг', '52227'); 
insert into ingredients(description, unit, art_by) values ('Морковь', 'кг', '50935'); 

